In [ ]:
# зависимости
%pip install pandas matplotlib anytree networkx -q

## EDA, предобработка датафрейма

**1. Прочитаем датасет, посмотрим на данные и пропуски, отберем только релевантные для анализа колонки (с данными по категориям продуктов).**

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("samokat_esci.csv")
data.head()

,query,item_name,item_id,final_answer,category4_name,category3_name,category2_name,category1_name
0,энергетик без сахара,"энергетик самокат, без сахара, с соком малины,...",55e4ae6a298cf3f69d8e07a92ec9e6a0,e,энергетические напитки,энергетические напитки,напитки,безалкогольные напитки
1,салат из рубца,"салат кх волкова а. п. деревенский, 150 г",b429835fc94f84edf3e319f01ce35274,s,салаты с майонезом,салаты,готовые блюда,кулинария
2,барилла,"макароны barilla, пенне ригате, 450 г",a2f84d68a96b5f95e3b72ff3f664e1e6,e,фигурные,"спагетти, фигурные",макаронные изделия,бакалея
3,краска для волос орех,"спрей-уход для наращенных волос tashe 250 мл, ...",227b20c1eee7ba92f52dfaf6fe9c05c4,c,натуральные краски для волос,краска для волос,средства по уходу за волосами,уход
4,творог мя,"творог козочка с облачка, 5%, мягкий, из козье...",05180ad0ea61952acd22c82f5740c47b,e,мягкий творог,творог,кисломолочные традиционные продукты,молочная продукция

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79774 entries, 0 to 79773
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   query           79774 non-null  object
 1   item_name       79774 non-null  object
 2   item_id         79774 non-null  object
 3   final_answer    79774 non-null  object
 4   category4_name  79774 non-null  object
 5   category3_name  79727 non-null  object
 6   category2_name  79194 non-null  object
 7   category1_name  79054 non-null  object
dtypes: object(8)
memory usage: 4.9+ MB

In [5]:
# пропущенные значения
data.isna().sum()

query               0
item_name           0
item_id             0
final_answer        0
category4_name      0
category3_name     47
category2_name    580
category1_name    720
dtype: int64

In [6]:
data_categories = data[['category4_name', 'category3_name', 'category2_name', 'category1_name']]

# сгруппируем по первой категории и посмотрим, где больше всего объектов
data_categories.groupby(['category1_name'], dropna=False).count().sort_values('category3_name', ascending=False)

,category4_name,category3_name,category2_name
category1_name,,,
уход,5271,5271,5271
безалкогольные напитки,4745,4745,4745
молочная продукция,4565,4565,4565
парфюмерия и декоративная косметика,4056,4056,4056
бакалея,3938,3938,3938
кулинария,3524,3524,3524
кондитерские изделия,3120,3120,3120
гигиена,2953,2953,2953
хлеб и хлебобулочные изделия,2895,2895,2895
одежда,2623,2623,2623
детские товары,2617,2617,2617
снэки,2534,2534,2534
ремонт и обустройство дома,2376,2376,2376
"книги, хобби, канцелярия",2215,2215,2215
замороженные продукты,2175,2175,2175
продукция для животных,2007,2007,2007
сыры,1998,1998,1998
бытовая химия,1885,1885,1885
детское питание,1859,1859,1859
мороженое и десерты,1785,1785,1785
мясная гастрономия,1634,1634,1634
мучные кондитерские изделия,1600,1600,1600
консервированные продукты,1579,1579,1579
свежие овощи,1475,1475,1475
птица,1380,1380,1380
обувь,1297,1297,1297
товары для дома,1157,1157,1157
"кофе, какао",1053,1053,1053
рыбная гастрономия,977,977,977
чай,937,937,937
аксессуары,802,802,802
свежие фрукты,732,732,732
детская гигиена и уход,721,721,721
мясо,709,709,709
NaN,720,673,140
компьютеры и аксессуары,515,515,515
смартфоны и гаджеты,462,462,462
спорт и активный отдых,430,430,430
бытовая техника и электроника,405,405,405
яичные товары,316,316,316
специальное питание,311,311,311
автомобильные товары и запчасти,253,253,253
праздничные и сезонные товары,252,252,252
хозяйственные товары,239,239,239
бады и витамины,103,103,103
товары для взрослых,98,98,98
посуда и кухонные принадлежности,88,88,88
строительство и ремонт,83,83,83
мебель,66,66,66
аптека,59,59,59
алкоголь,52,52,52
рынок,26,26,26
маркетинг товары промо,25,25,25
слабоалкогольные напитки,23,23,23
рыба охлажденная,22,22,22
комплектующие для продажи,13,13,13
имущество магазина,7,7,7
образцы товаров,5,5,5
товары для пикника,5,5,5
табачные изделия,2,2,2

**2. Проанализируем, когда возникают пропущенные значения.**

In [7]:
data_categories_null = data_categories[data_categories.isna().any(axis=1)]
data_categories_null.head()

,category4_name,category3_name,category2_name,category1_name
65,материалы,имущество магазина,NaN,NaN
144,сэмплы,прочее,NaN,NaN
223,сканеры штрих-кода для внутренних нужд,ит оборудование,имущество магазина,NaN
260,комплектующие для продажи,NaN,NaN,NaN
288,мерч униформа,мерч,имущество магазина,NaN

Получается, что если путь более короткий, чем 4 категории, то колонки занимаются, начиная с category4_name.

Посмотрим на одноуровневые категории и проверим, что там находится.

In [8]:
data_categories_null[data_categories_null.isna().sum(axis=1) == 3]['category4_name'].value_counts()

category4_name
услуги                       23
комплектующие для продажи    11
собственные отходы            9
! на удаление !               3
упаковка                      1
Name: count, dtype: int64

## Дерево категорий

**Задача: визуализировать иерархию категорий. Какие категории самые крупные, как устроено дерево?**

**1. Преобразуем датафрейм.**

- Пропуски в категориях на более высоких уровнях заполняются данными с более назких
- В датафрейме хранятся только уникальные строки (наборы категорий) с указанием того, сколько раз они встретились в датафрейме.

In [9]:
data_categories_fillna = data_categories.copy()

# заполняем пропущенные категории снизу вверх
data_categories_fillna['category3_name'] = data_categories_fillna['category3_name'].fillna(data_categories_fillna['category4_name'])
data_categories_fillna['category2_name'] = data_categories_fillna['category2_name'].fillna(data_categories_fillna['category3_name'])
data_categories_fillna['category1_name'] = data_categories_fillna['category1_name'].fillna(data_categories_fillna['category2_name'])

# версия датасета с подсчетом уникальных строк
data_categories_counted = data_categories_fillna.copy()
data_categories_counted['count'] = data_categories_counted.groupby(list(data_categories.columns)).transform('size')
data_categories_counted = data_categories_counted.drop_duplicates()

data_categories_counted.head()

,category4_name,category3_name,category2_name,category1_name,count
0,энергетические напитки,энергетические напитки,напитки,безалкогольные напитки,589
1,салаты с майонезом,салаты,готовые блюда,кулинария,145
2,фигурные,"спагетти, фигурные",макаронные изделия,бакалея,228
3,натуральные краски для волос,краска для волос,средства по уходу за волосами,уход,96
4,мягкий творог,творог,кисломолочные традиционные продукты,молочная продукция,45

**2. Соберем связи по уровням категорий и построим дерево.**

In [10]:
from anytree import Node, RenderTree

def create_connections(df, cols=['category4_name', 'category3_name', 'category2_name', 'category1_name', 'count']):
    """Функция, собирающая все направленные связи по категориям"""

    connections = []

    # для каждой строки добавляем все последовательные пары с весами
    for index, row in df.iterrows():
        for i in range(1, len(cols)-1):
            # от большей категории - к меньшей - вес
            if not row[cols[i]] == row[cols[i-1]]:
                connections.append([row[cols[i]], row[cols[i-1]], row['count']])
                # print(index, row[cols[i-1]], row[cols[i]])

    connections = sorted(connections, key=lambda x: [x[0], x[1]])
    print(connections)

    # объединяем повторяющиеся ребра и суммируем значения
    merged = []
    for conn in connections:
        if not merged or merged[-1][:-1] != conn[:-1]:
            merged.append(conn)
        else:
            merged[-1][2] += conn[2]
            
    return merged


def create_tree(edges):
    """Функция, создающая дерево категорий"""
    nodes = {}

    for parent_name, child_name in edges:
        try:
            # создаем узел родителя
            if parent_name not in nodes:
                nodes[parent_name] = Node(parent_name)
            
            # создаем узел ребенка
            if child_name not in nodes:
                nodes[child_name] = Node(child_name)
            
            # назначаем связь
            nodes[child_name].parent = nodes[parent_name]
        except Exception as e:
            print(e)

    return nodes


def draw_tree(nodes):
    """Функция отрисовки дерева"""
    # ищем корневые узлы и визуализируем
    root = None
    for node in nodes.values():
        if node.is_root:
            root = node
            for pre, fill, node in RenderTree(root):
                print(f"{pre}{node.name}")
            print('\n')

In [11]:
edges = create_connections(data_categories_counted)
edges = [i[:-1] for i in edges]
tree = create_tree(edges)
draw_tree(tree)

[['it/office', 'мобильные и стационарные компьютеры', 12], ['it/office', 'мобильные и стационарные компьютеры', 11], ['it/office', 'мобильные и стационарные компьютеры', 13], ['it/office', 'мобильные и стационарные компьютеры', 4], ['it/office', 'мобильные и стационарные компьютеры', 3], ['it/office', 'мобильные и стационарные компьютеры', 2], ['it/office', 'мобильные и стационарные компьютеры', 7], ['it/office', 'мобильные и стационарные компьютеры', 4], ['it/office', 'мобильные и стационарные компьютеры', 3], ['it/office', 'мониторы', 6], ['it/office', 'оргтехника', 7], ['it/office', 'оргтехника', 3], ['it/office', 'оргтехника', 1], ['it/office', 'офисная периферия', 19], ['it/office', 'офисная периферия', 8], ['it/office', 'офисная периферия', 6], ['it/office', 'офисная периферия', 2], ['it/office', 'сетевое оборудование', 6], ['it/office', 'сетевое оборудование', 3], ['telecom', 'аудиотехника для гаджетов', 48], ['telecom', 'аудиотехника для гаджетов', 28], ['telecom', 'аудиотехника для гаджетов', 11], ['telecom', 'операторы сотовой связи', 1], ['telecom', 'операторы сотовой связи', 8], ['telecom', 'операторы сотовой связи', 2], ['telecom', 'планшеты wi-fi', 1], ['авто свет и лампы', 'автомобильные лампы', 3], ['автоаккумуляторы и зарядные устройства для автомобилей', 'аккумуляторы и зарядные устройства', 1], ['автокосметика и автохимия', 'ароматизаторы в машину', 49], ['автокосметика и автохимия', 'герметики, клеи', 17], ['автокосметика и автохимия', 'герметики, клеи', 5], ['автокосметика и автохимия', 'герметики, клеи', 5], ['автокосметика и автохимия', 'кузов', 4], ['автокосметика и автохимия', 'кузов', 2], ['автокосметика и автохимия', 'кузов', 1], ['автокосметика и автохимия', 'кузов', 1], ['автокосметика и автохимия', 'кузов', 2], ['автокосметика и автохимия', 'очистители салона', 4], ['автокосметика и автохимия', 'очистители салона', 4], ['автокосметика и автохимия', 'прочая автохимия', 4], ['автокосметика и автохимия', 'салфетки для авто', 3], ['автокосметика и автохимия', 'смазки', 1], ['автокосметика и автохимия', 'смазки', 6], ['автокосметика и автохимия', 'смазки', 1], ['автокосметика и автохимия', 'уход за автомобилем', 2], ['автокосметика и автохимия', 'уход за автомобилем', 1], ['автокосметика и автохимия', 'уход и ремонт шин и дисков', 2], ['автокосметика и автохимия', 'уход и ремонт шин и дисков', 3], ['автокосметика и автохимия', 'фары и стекла', 5], ['автокосметика и автохимия', 'фары и стекла', 1], ['автокосметика и автохимия', 'фары и стекла', 1], ['автомобильная электроника', 'доп. оборудование для автоэлектроники', 5], ['автомобильная электроника', 'навигаторы, радар-детекторы и регистраторы', 9], ['автомобильная электроника', 'навигаторы, радар-детекторы и регистраторы', 15], ['автомобильная электроника', 'навигаторы, радар-детекторы и регистраторы', 1], ['автомобильные товары', 'авто свет и лампы', 3], ['автомобильные товары', 'автоаккумуляторы и зарядные устройства для автомобилей', 1], ['автомобильные товары', 'автопринадлежности', 2], ['автомобильные товары', 'автопринадлежности', 1], ['автомобильные товары', 'аксессуары для автомобилей', 1], ['автомобильные товары', 'аксессуары для автомобилей', 7], ['автомобильные товары', 'аксессуары для автомобилей', 7], ['автомобильные товары', 'аксессуары для автомобилей', 2], ['автомобильные товары', 'аксессуары для автомобилей', 1], ['автомобильные товары', 'дополнительное оборудование', 2], ['автомобильные товары', 'пленки для автомобилей', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 49], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 4], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 17], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 5], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 2], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 3], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 4], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 2], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 4], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 6], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 5], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 3], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 5], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 2], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 4], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 1], ['автомобильные товары и запчасти', 'автокосметика и автохимия', 2], ['автомобильные товары и запчасти', 'автомобильная электроника', 9], ['автомобильные товары и запчасти', 'автомобильная электроника', 15], ['автомобильные товары и запчасти', 'автомобильная электроника', 5], ['автомобильные товары и запчасти', 'автомобильная электроника', 1], ['автомобильные товары и запчасти', 'автомобильные товары', 2], ['автомобильные товары и запчасти', 'автомобильные товары', 1], ['автомобильные товары и запчасти', 'автомобильные товары', 7], ['автомобильные товары и запчасти', 'автомобильные товары', 3], ['автомобильные товары и запчасти', 'автомобильные товары', 2], ['автомобильные товары и запчасти', 'автомобильные товары', 7], ['автомобильные товары и запчасти', 'автомобильные товары', 1], ['автомобильные товары и запчасти', 'автомобильные товары', 2], ['автомобильные товары и запчасти', 'автомобильные товары', 1], ['автомобильные товары и запчасти', 'автомобильные товары', 1], ['автомобильные товары и запчасти', 'автомобильные товары', 1], ['автомобильные товары и запчасти', 'запчасти', 57], ['автомобильные товары и запчасти', 'запчасти', 2], ['автомобильные товары и запчасти', 'запчасти', 1], ['автомобильные товары и запчасти', 'масла, технические жидкости', 2], ['автомобильные товары и запчасти', 'масла, технические жидкости', 9], ['автопринадлежности', 'принадлежности для мытья и очистки от снега', 1], ['автопринадлежности', 'специализированные автомобильный инструмент', 2], ['аккумуляторы, зарядные устройства', 'аккумуляторы', 1], ['аккумуляторы, зарядные устройства', 'зарядные устройства д/аккумуляторов', 1], ['аккумуляторы, зарядные устройства', 'наборы аккумуляторов и зарядных устройств', 2], ['аксессуары', 'аксессуары для волос', 30], ['аксессуары', 'аксессуары для волос', 38], ['аксессуары', 'аксессуары для волос', 3], ['аксессуары', 'аксессуары для волос', 6], ['аксессуары', 'аксессуары для волос', 12], ['аксессуары', 'аксессуары для волос', 14], ['аксессуары', 'аксессуары для лица и тела', 25], ['аксессуары', 'аксессуары для очистки кистей', 8], ['аксессуары', 'аксессуары для путешествий', 3], ['аксессуары', 'аксессуары для путешествий', 5], ['аксессуары', 'аксессуары для путешествий', 3], ['аксессуары', 'аксессуары прочие', 52], ['аксессуары', 'аксессуары прочие', 7], ['аксессуары', 'аксессуары прочие', 11], ['аксессуары', 'аксессуары прочие', 9], ['аксессуары', 'аксессуары прочие', 5], ['аксессуары', 'аксессуары прочие', 1], ['аксессуары', 'бижутерия', 56], ['аксессуары', 'бижутерия', 23], ['аксессуары', 'бижутерия', 11], ['аксессуары', 'бижутерия', 62], ['аксессуары', 'бижутерия', 6], ['аксессуары', 'бижутерия', 29], ['аксессуары', 'головные уборы', 14], ['аксессуары', 'головные уборы', 13], ['аксессуары', 'головные уборы', 7], ['аксессуары', 'головные уборы', 2], ['аксессуары', 'головные уборы', 9], ['аксессуары', 'головные уборы', 3], ['аксессуары', 'головные уборы', 1], ['аксессуары', 'головные уборы', 2], ['аксессуары', 'головные уборы', 1], ['аксессуары', 'головные уборы', 1], ['аксессуары', 'зонты и дождевики', 6], ['аксессуары', 'кисти для бровей', 19], ['аксессуары', 'кисти для глаз', 32], ['аксессуары', 'кисти для губ', 5], ['аксессуары', 'кисти для лица', 72], ['аксессуары', 'клей для накладных ресниц', 14], ['аксессуары', 'наборы аксессуаров', 2], ['аксессуары', 'наборы кистей', 4], ['аксессуары', 'наборы накладных ресниц', 5], ['аксессуары', 'накладные ресницы', 20], ['аксессуары', 'очки и аксессуары', 16], ['аксессуары', 'переводные тату', 16], ['аксессуары', 'перчатки и варежки', 25], ['аксессуары', 'перчатки и варежки', 2], ['аксессуары', 'перчатки и варежки', 1], ['аксессуары', 'ремни и пояса', 47], ['аксессуары', 'ремни и пояса', 50], ['аксессуары', 'спонжи', 47], ['аксессуары', 'стразы и кристаллы', 6], ['аксессуары', 'сумки и рюкзаки', 135], ['аксессуары', 'сумки и рюкзаки', 43], ['аксессуары', 'сумки и рюкзаки', 4], ['аксессуары', 'сумки и рюкзаки', 6], ['аксессуары', 'сумки и рюкзаки', 1], ['аксессуары', 'трафареты', 3], ['аксессуары', 'футляры', 18], ['аксессуары', 'часы и аксессуары', 25], ['аксессуары', 'шарфы и платки', 2], ['аксессуары для автомобилей', 'аксессуары в салон автомобиля', 2], ['аксессуары для автомобилей', 'крепления и держатели', 7], ['аксессуары для автомобилей', 'органайзеры для автомобилей', 7], ['аксессуары для автомобилей', 'рамки под номер', 1], ['аксессуары для автомобилей', 'чехлы и накидки на сиденья', 1], ['аксессуары для бани', 'банная станция', 21], ['аксессуары для бани', 'ведро для бани', 1], ['аксессуары для бани', 'вешалка для бани', 1], ['аксессуары для бани', 'ковш для бани', 3], ['аксессуары для бани', 'массажер для бани', 9], ['аксессуары для бани', 'мочалка для бани', 6], ['аксессуары для бани', 'светильник для бани', 1], ['аксессуары для бани', 'табличка для бани', 1], ['аксессуары для бани', 'термометр банный', 10], ['аксессуары для бани', 'часы для бани', 13], ['аксессуары для бани', 'шайка', 5], ['аксессуары для ванной комнаты', 'аксессуары для ванной прочее', 16], ['аксессуары для ванной комнаты', 'аксессуары для ванной прочее', 13], ['аксессуары для ванной комнаты', 'дозатор для мыла', 35], ['аксессуары для ванной комнаты', 'дозатор для мыла', 3], ['аксессуары для ванной комнаты', 'коврик для ванной комнаты', 14], ['аксессуары для ванной комнаты', 'крючок для ванной', 8], ['аксессуары для ванной комнаты', 'мыльница', 24], ['аксессуары для ванной комнаты', 'мыльница', 10], ['аксессуары для ванной комнаты', 'наборы для ванной комнаты', 8], ['аксессуары для ванной комнаты', 'наборы для ванной комнаты', 1], ['аксессуары для ванной комнаты', 'органайзер для ванной', 4], ['аксессуары для ванной комнаты', 'полка для ванной', 3], ['аксессуары для ванной комнаты', 'стакан для зубных щеток', 11], ['аксессуары для ванной комнаты', 'шторы и карнизы для ванной', 2], ['аксессуары для волос', 'заколки', 30], ['аксессуары для волос', 'заколки', 6], ['аксессуары для волос', 'заколки', 14], ['аксессуары для волос', 'ободки', 3], ['аксессуары для волос', 'повязки', 12], ['аксессуары для волос', 'расчески', 59], ['аксессуары для волос', 'резинки', 38], ['аксессуары для волос', 'резинки, заколки', 1], ['аксессуары для детей', 'варежки и перчатки', 7], ['аксессуары для детей', 'головные уборы', 7], ['аксессуары для детей', 'головные уборы', 11], ['аксессуары для детей', 'детская бижутерия', 35], ['аксессуары для детей', 'детские аксессуары для волос', 79], ['аксессуары для детей', 'прочие детские аксессуары', 25], ['аксессуары для детей', 'рюкзаки', 2], ['аксессуары для детей', 'сумки', 16], ['аксессуары для детей', 'шарфы', 1], ['аксессуары для кормления', 'бутылочки', 80], ['аксессуары для кормления', 'соски', 5], ['аксессуары для крупно бытовой техники', 'аксессуары для плит и духовок', 1], ['аксессуары для лица и тела', 'аксессуары для тела', 3], ['аксессуары для лица и тела', 'аксессуары для умывания', 18], ['аксессуары для лица и тела', 'массажеры', 52], ['аксессуары для обуви', 'ложка, рожок для обуви', 1], ['аксессуары для обуви', 'подушечки для обуви', 1], ['аксессуары для обуви', 'стельки', 10], ['аксессуары для освещения', 'комплектующие и лампочки', 21], ['аксессуары для путешествий', 'аксессуары для путешествий и поездок', 3], ['аксессуары для путешествий', 'прочие аксессуары для путешествий', 5], ['аксессуары для путешествий', 'чемоданы и дорожные сумки', 3], ['аксессуары для путешествий и поездок', 'маска для сна', 3], ['аксессуары для садовой мебели', 'матрас для шезлонга', 2], ['аксессуары для садовой мебели', 'насос для надувной мебели', 5], ['аксессуары для сервировки', 'аксессуары для сервировки прочее', 7], ['аксессуары для сервировки', 'аксессуары для сервировки прочее', 2], ['аксессуары для сервировки', 'зубочистки и подставки для зубочисток', 26], ['аксессуары для сервировки', 'поднос', 1], ['аксессуары для сервировки', 'формы для льда', 19], ['аксессуары для сервировки', 'формы для льда', 17], ['аксессуары для смарт-часов и браслетов', 'ремешки для смарт-часов', 4], ['аксессуары для смартфонов', 'кабели, переходники, зу', 2], ['аксессуары для смартфонов', 'чехлы, пленки, защитные стекла', 61], ['аксессуары для спортивного питания', 'спортивные бутылки и шейкеры', 10], ['аксессуары для спортивного питания', 'таблетницы и контейнеры', 13], ['аксессуары для суши', 'циновка', 1], ['аксессуары для телевизоров', 'медиаплееры', 1], ['аксессуары для телевизоров', 'телевизионные антенны', 1], ['аксессуары для телефонов и планшетов', 'гарнитуры', 9], ['аксессуары для телефонов и планшетов', 'дополнительные аксессуары', 9], ['аксессуары для телефонов и планшетов', 'кабели для телефонов и планшетов', 132], ['аксессуары для ухода', 'аксессуары для лица и тела', 18], ['аксессуары для ухода', 'аксессуары для лица и тела', 52], ['аксессуары для ухода', 'аксессуары для лица и тела', 3], ['аксессуары для ухода за обувью', 'краска для обуви', 1], ['аксессуары для ухода за обувью', 'сушилки для обуви', 1], ['аксессуары и игрушки', 'амуниция для собак', 7], ['аксессуары и игрушки', 'амуниция для собак', 11], ['аксессуары и игрушки', 'амуниция для собак', 4], ['аксессуары и игрушки', 'амуниция для собак', 10], ['аксессуары и игрушки', 'игрушки для кошек', 8], ['аксессуары и игрушки', 'игрушки для кошек', 3], ['аксессуары и игрушки', 'игрушки для собак', 23], ['аксессуары и игрушки', 'игрушки для собак', 6], ['аксессуары и игрушки', 'игрушки для собак', 14], ['аксессуары и игрушки', 'коррекция поведения и поглотители запаха', 1], ['аксессуары и игрушки', 'лежаки и домики для кошек', 5], ['аксессуары и игрушки', 'лежаки и домики для кошек', 2], ['аксессуары и игрушки', 'лежаки и домики для собак', 2], ['аксессуары и игрушки', 'переноски', 8], ['аксессуары и игрушки', 'товары для кормления кошек', 2], ['аксессуары и игрушки', 'товары для кормления кошек', 1], ['аксессуары и игрушки', 'товары для кормления собак', 8], ['аксессуары общие', 'аксессуары разное', 1], ['аксессуары общие', 'галстук', 5], ['аксессуары прочие', 'аксессуары общие', 5], ['аксессуары прочие', 'аксессуары общие', 1], ['аксессуары прочие', 'косметички', 7], ['аксессуары прочие', 'кошельки и картхолдеры', 52], ['аксессуары прочие', 'кошельки и картхолдеры', 11], ['аксессуары прочие', 'обложки для документов', 9], ['алкоголь', 'вино', 3], ['алкоголь', 'вино', 13], ['алкоголь', 'вино', 1], ['алкоголь', 'вино', 13], ['алкоголь', 'вино', 1], ['алкоголь', 'вино', 1], ['алкоголь', 'вино', 1], ['алкоголь', 'вино', 2], ['алкоголь', 'крепкий алкоголь', 4], ['алкоголь', 'крепкий алкоголь', 1], ['алкоголь', 'крепкий алкоголь', 1], ['алкоголь', 'крепкий алкоголь', 2], ['алкоголь', 'крепкий алкоголь', 2], ['алкоголь', 'крепкий алкоголь', 1], ['алкоголь', 'крепкий алкоголь', 1], ['алкоголь', 'крепкий алкоголь', 3], ['алкоголь', 'крепкий алкоголь', 1], ['алкоголь', 'крепкий алкоголь', 1], ['аминокислоты и bcaa', 'bcaa', 1], ['амуниция для собак', 'намордники', 10], ['амуниция для собак', 'ошейники для собак', 7], ['амуниция для собак', 'поводки и шлейки', 11], ['амуниция для собак', 'рулетки', 4], ['аптека', 'оптические линзы и растворы', 51], ['аптека', 'оптические линзы и растворы', 8], ['ароматизаторы в машину', 'автомобильный ароматизатор', 49], ['ассорти круп', 'готовые смеси круп и бобов', 38], ['ассорти круп', 'смеси для приготовления супа', 56], ['аудиотехника', 'виниловые проигрыватели', 1], ['аудиотехника', 'портативные колонки', 8], ['аудиотехника', 'портативные плееры', 1], ['аудиотехника', 'умные колонки', 12], ['аудиотехника', 'умные колонки яндекс', 10], ['аудиотехника для гаджетов', 'наушники apple', 11], ['аудиотехника для гаджетов', 'наушники tws', 48], ['аудиотехника для гаджетов', 'проводные наушники и гарнитуры для телефонов', 28], ['бадминтон', 'воланы для бадминтона', 1], ['бады', 'бады для женского здоровья', 5], ['бады', 'бады для жкт', 1], ['бады', 'бады для здорового сна', 19], ['бады', 'бады для иммунитета', 11], ['бады', 'бады для костей и суставов', 8], ['бады', 'бады для красоты', 4], ['бады', 'бады для мужского здоровья', 1], ['бады', 'бады для нервной системы', 7], ['бады', 'бады для памяти, внимания', 1], ['бады', 'бады для похудения', 3], ['бады', 'бады для почек, печени', 1], ['бады', 'бады для сердца, сосудов', 2], ['бады', 'бады для спорта и фитнеса', 1], ['бады', 'бады прочие', 27], ['бады и витамины', 'бады', 19], ['бады и витамины', 'бады', 8], ['бады и витамины', 'бады', 27], ['бады и витамины', 'бады', 1], ['бады и витамины', 'бады', 3], ['бады и витамины', 'бады', 5], ['бады и витамины', 'бады', 11], ['бады и витамины', 'бады', 7], ['бады и витамины', 'бады', 1], ['бады и витамины', 'бады', 4], ['бады и витамины', 'бады', 1], ['бады и витамины', 'бады', 2], ['бады и витамины', 'бады', 1], ['бады и витамины', 'бады', 1], ['бады и витамины', 'витамины', 10], ['бады и витамины', 'витамины', 1], ['бады и витамины', 'витамины', 1], ['бакалея', 'все для суши', 34], ['бакалея', 'все для суши', 1], ['бакалея', 'все для суши', 1], ['бакалея', 'все для суши', 4], ['бакалея', 'все для суши', 1], ['бакалея', 'зерновые для завтраков', 76], ['бакалея', 'зерновые для завтраков', 60], ['бакалея', 'зерновые для завтраков', 86], ['бакалея', 'зерновые для завтраков', 86], ['бакалея', 'зерновые для завтраков', 19], ['бакалея', 'зерновые для завтраков', 15], ['бакалея', 'зерновые для завтраков', 57], ['бакалея', 'зерновые для завтраков', 71], ['бакалея', 'зерновые для завтраков', 31], ['бакалея', 'зерновые для завтраков', 2], ['бакалея', 'зерновые для завтраков', 2], ['бакалея', 'ингредиенты для готовки', 21], ['бакалея', 'ингредиенты для готовки', 10], ['бакалея', 'ингредиенты для готовки', 17], ['бакалея', 'ингредиенты для готовки', 9], ['бакалея', 'ингредиенты для готовки', 5], ['бакалея', 'ингредиенты для готовки', 5], ['бакалея', 'ингредиенты для готовки', 3], ['бакалея', 'ингредиенты для готовки', 17], ['бакалея', 'ингредиенты для готовки', 12], ['бакалея', 'ингредиенты для готовки', 33], ['бакалея', 'ингредиенты для готовки', 8], ['бакалея', 'ингредиенты для готовки', 6], ['бакалея', 'ингредиенты для готовки', 6], ['бакалея', 'ингредиенты для готовки', 9], ['бакалея', 'ингредиенты для готовки', 7], ['бакалея', 'ингредиенты для готовки', 1], ['бакалея', 'ингредиенты для готовки', 3], ['бакалея', 'ингредиенты для готовки', 3], ['бакалея', 'крупы, бобовые', 14], ['бакалея', 'крупы, бобовые', 23], ['бакалея', 'крупы, бобовые', 50], ['бакалея', 'крупы, бобовые', 56], ['бакалея', 'крупы, бобовые', 17], ['бакалея', 'крупы, бобовые', 31], ['бакалея', 'крупы, бобовые', 38], ['бакалея', 'крупы, бобовые', 46], ['бакалея', 'крупы, бобовые', 6], ['бакалея', 'крупы, бобовые', 76], ['бакалея', 'крупы, бобовые', 23], ['бакалея', 'крупы, бобовые', 13], ['бакалея', 'крупы, бобовые', 16], ['бакалея', 'крупы, бобовые', 7], ['бакалея', 'крупы, бобовые', 38], ['бакалея', 'крупы, бобовые', 2], ['бакалея', 'крупы, бобовые', 3], ['бакалея', 'крупы, бобовые', 10], ['бакалея', 'крупы, бобовые', 6], ['бакалея', 'крупы, бобовые', 7], ['бакалея', 'крупы, бобовые', 13], ['бакалея', 'крупы, бобовые', 1],

**3. Визулизируем дерево в графовом формате.**